### ISSUE TITLE
How to get Human3.6m joint regressor if H3.6M ground truth SMPL is not available?

### ISSUE THREAD

**Issue by xy-guo** [nkolot/SPIN#1]

**Comment by geopavlakos** [comment]
By running the ```fetch_data.sh``` script, you will get the joint regressor in the ```data``` folder. You will need this only for evaluation purposes.

**Comment by xy-guo** [comment]
May I ask how you train the regressor? It seems the only way is to train with ground truth SMPL of human 3.6M SMPL.

**Comment by geopavlakos** [comment]
We train the regressor using SMPL parameters (estimated by MoSh) for Human3.6M. This is not considered ground truth, but it is good enough for our purposes.

**Comment by xy-guo** [comment]
If there is no mocap data, for example OpenPose joints or other 2d-only dataset, how to train the regressor?

**Comment by geopavlakos** [comment]
Regarding common joints that are available in other datasets, in most cases we correspond them to one of the original SMPL joints. Some vertex correspondences (e.g., ears, eyes, etc) are manually defined.

**Comment by xy-guo** [comment]
Thanks!
