### ISSUE TITLE
How can I get the Sup.Mat.?

### ISSUE THREAD

**Issue by ypflll** [nkolot/SPIN#14]
Not found in the project page.

**Comment by nkolot** [comment]
https://www.seas.upenn.edu/~nkolot/projects/spin/files/spin-supp.pdf

**Comment by ypflll** [comment]
Hi, @nkolot ,
I am not very clear about the joint number you use in Table3 of your paper.
Do you use the regressor form SMPLify(19/14) or the 16 joints in SMPL?

**Comment by geopavlakos** [comment]
We use the 14 common joints that are typically used for evaluation in this protocol by methods employing the SMPL model. You can look at the exact evaluation procedure we follow in the eval.py script we provide.

**Comment by ypflll** [comment]
@geopavlakos That's very clear and thanks.
