### ISSUE TITLE
`FileNotFoundError` in colab notebook

### ISSUE THREAD

**Issue by amrzv** [nkolot/SPIN#140]
Hello.
The [basicModel_neutral_lbs_10_207_0_v1.0.0.pkl](https://github.com/classner/up/raw/master/models/3D/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl) is no longer avaiilable. As a result, colab [notebook ](https://colab.research.google.com/drive/1uH2JtavOtDrFl6RsipyIncCSr19GWW4x?usp=sharing#scrollTo=imU_02GmcQo8)doesn't work because of `FileNotFoundError`.

Author [removed ](https://github.com/classner/up/commit/944d1e38d309995441402c0ccf46f21a1fde8908) the `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` recently.

![image](https://github.com/nkolot/SPIN/assets/36787333/b2aa7f17-5d9d-47d6-b2b7-42c62be01f12)

**Comment by geopavlakos** [comment]
You can download the `basicModel_neutral_lbs_10_207_0_v1.0.0.pkl` file from [https://smplify.is.tue.mpg.de/](https://smplify.is.tue.mpg.de/). Please register, sign in and download the file. Then, you can put it in your colab environment.
