### ISSUE TITLE
Replace smpl model with smpl-x

### ISSUE THREAD

**Issue by Thushar-marvel** [nkolot/SPIN#141]
Is it possible to change the  3d model from SMPL to SMPL-X for better accuracy?

**Comment by geopavlakos** [comment]
This requires retraining the network using SMPL-X as a target (images with SMPL-X ground truth or pseudo ground truth), so it's possible, but not trivial.

**Comment by Thushar-marvel** [comment]
> This requires retraining the network using SMPL-X as a target (images with SMPL-X ground truth or pseudo ground truth), so it's possible, but not trivial.

Thanks. @geopavlakos
