### ISSUE TITLE
run demo.py, ERROR: path data/smpl/SMPL_NEURAL.pkl does not exist!

### ISSUE THREAD

**Issue by LH-Abner** [nkolot/SPIN#15]
hi , I can not find the SMPL_NEURAL.pkl. When I run demo.py., there is a mistake. How can I get the SMPL_NEURAL.pkl. thanks!

**Comment by ikvision** [comment]
After downloading the smpl neutral model you need to rename it:
mv ./data/smpl/basicModel_neutral_lbs_10_207_0_v1.0.0.pkl ./data/smpl/SMPL_NEUTRAL.pkl

**Comment by LH-Abner** [comment]
OK , it is fine.Thanks!
