### ISSUE TITLE
About the initial and final static fits.

### ISSUE THREAD

**Issue by xy-guo** [nkolot/SPIN#18]
Why the download link for the initial fits and the final fits seem to be the same? Both links are [http://visiondata.cis.upenn.edu/spin/static_fits.tar.gz](http://visiondata.cis.upenn.edu/spin/static_fits.tar.gz)

**Comment by xuxy09** [comment]
Nice point. I am also confused about the same issue. 
In addition, could you please clarify whether the fits provided here are initialized from [21] or the mean pose? 
Thanks!

**Comment by geopavlakos** [comment]
Thanks for pointing this out! The link in the README has been updated.
The static fits provided here are initialized from [21].

**Comment by xuxy09** [comment]
Thanks a lot!

**Comment by xuxy09** [comment]
I find that there is one file missing in the updated link: "mpi-inf-3dhp_mview_fits.npz". Is this file useful in your project? Could you please elaborate more on what this file is?

**Comment by geopavlakos** [comment]
This file is only part of the initial static fits, not of the final spin fits. Therefore, it is not missing from the compressed file of the updated link, it is just not supposed to be there.
