### ISSUE TITLE
can't download SMPL_python_v.1.0.0.zip in notebook

### ISSUE THREAD

**Issue by hijason1301** [nkolot/SPIN#19]
in notbook file

# http://smpl.is.tue.mpg.de/ (Neutral Model)
#!wget http://smpl.is.tue.mpg.de -O SMPL_python_v.1.0.0.zip
!unzip SMPL_python_v.1.0.0.zip -d data && rm -rf data/__MACOSX && rm -r SMPL_python_v.1.0.0.zip
it dosen't work

please help. thanks

**Comment by geopavlakos** [comment]
The above website (SMPL project website) requires registering to be able to download the relevant material. I would suggest registering and manually downloading all the files you need from there.

**Comment by salmedina** [comment]
When I download the models from [smpl.is.tue.mpg.de](http://smpl.is.tue.mpg.de/) I only see the female and male models. Where can I get the neutral model?

**Comment by geopavlakos** [comment]
You can get the neutral model from the [SMPLify project page](http://smplify.is.tue.mpg.de). Again, you need to register to access the Downloads.
