### ISSUE TITLE
typo in constants.py

### ISSUE THREAD

**Issue by yin-zhang** [nkolot/SPIN#21]
I see the following line in constants.py:

J24_TO_J17 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 18, 14, 16, 17]

should 18 be 13 instead?

**Comment by yin-zhang** [comment]
It seems that the 14-th keypoint in LSP is "Top of Head", which corresponds to index 13 in the 24 joints

**Comment by nkolot** [comment]
Keypoint 13 is the LSP definition of the head whereas keypoint 18 is the H36m definition of the head. There is a difference between these 2; LSP uses the top of the head whereas H36m defines the head somewhere inside the head. For H36m evaluation it's better to use the H36m definition.

**Comment by yin-zhang** [comment]
Thanks a lot!
