### ISSUE TITLE
relationship between J_regressor_h36m.npy and J_regressor_extra.npy

### ISSUE THREAD

**Issue by yin-zhang** [nkolot/SPIN#22]
I notice J_regressor_extra[7,:] == J_regressor_h36m[9,:], which is Jaw (H36M), and J_regressor_extra[6,:] == J_regressor_h36m[7,:], which is Spine (H36M).

However, J_regressor_extra[8,:] and J_regressor_h36m[10,:] are quite different, although they are both supposed to be Head (H36M).  Is there any reason for this?

**Comment by yin-zhang** [comment]
Dear author, 

Do you have any insight on this?  Thanks a ton!

-- Yin

**Comment by geopavlakos** [comment]
There is indeed some difference for this joint. For the regressor we use for training, this joint is taken from the definition of the [HMR repo](https://github.com/akanazawa/hmr), whereas the definition of the joint we use for evaluation is slightly different. If you compare the values of the regressor, they look very different, but if you apply the regressors on a mesh and visualize the two points, you will see that they are pretty close in 3D. In the end, this inconsistency should have very small effect in the training of the model.

**Comment by liwenssss** [comment]
so ,why use different joint?

**Comment by geopavlakos** [comment]
This was part of a legacy code and it was not updated to avoid any inconsistencies.
