### ISSUE TITLE
Question about shape prior of smplify

### ISSUE THREAD

**Issue by iammarvelous** [nkolot/SPIN#26]
Thanks for sharing the code. I have a question about shape prior in smplify implementation. Specifically, it seems that [this](https://github.com/nkolot/SPIN/blob/master/smplify/losses.py#L51) is a L2 regularizer. In the [paper](https://arxiv.org/pdf/1607.08128.pdf) (eq. (7)), they said `Σ` is a diagonal matrix with the squared singular values estimated via Principal Component Analysis from the shapes in the SMPL training set. In the implementation, it seems to imply the matrix is an identity matrix?

**Comment by nkolot** [comment]
You can file a detailed answer in [this](https://ps.is.tuebingen.mpg.de/uploads_file/attachment/attachment/392/Embodied_Hands_SiggraphAsia2017.pdf) paper.

More specifically, paragraph 5 of Section 3.2.

**Comment by iammarvelous** [comment]
Thanks. That answers my question.
