### ISSUE TITLE
Does No Pretrain checkpoint?

### ISSUE THREAD

**Issue by AIML** [nkolot/SPIN#28]

**Comment by ZGX010** [comment]
the pretrain checkpoint is in this 
# Script that fetches all necessary data for training and eval

# Model constants etc.
wget http://visiondata.cis.upenn.edu/spin/data.tar.gz && tar -xvf data.tar.gz && rm data.tar.gz
# Initial fits to start training
wget http://visiondata.cis.upenn.edu/spin/static_fits.tar.gz && tar -xvf static_fits.tar.gz --directory data && rm -r static_fits.tar.gz
# List of preprocessed .npz files for each dataset
wget http://visiondata.cis.upenn.edu/spin/dataset_extras.tar.gz && tar -xvf dataset_extras.tar.gz --directory data && rm -r dataset_extras.tar.gz
# Pretrained checkpoint

> wget http://visiondata.cis.upenn.edu/spin/model_checkpoint.pt --directory-prefix=data

# GMM prior from vchoutas/smplify0x
wget https://github.com/vchoutas/smplify-x/raw/master/smplifyx/prior.py -O smplify/prior.py

**Comment by geopavlakos** [comment]
If you run `./fetch_data.sh` you should get the pretrained model along with the other data you need to run our code.

**Comment by AIML** [comment]
I'm sorry for my carelessness，thanks for help
