### ISSUE TITLE
details about MPJPE and re-construction error calculate

### ISSUE THREAD

**Issue by liwenssss** [nkolot/SPIN#29]
Hi, I read the code , but I didn't know the details about MPJPE and re-construction error calculation.So is there any where I can get why to do that as the code show.

**Comment by geopavlakos** [comment]
The file eval.py includes all the details about how to compute the errors.
As far as why these errors are presented, this is what each dataset, or previous papers have set as the standard for the evaluation.

**Comment by liwenssss** [comment]
when calculate 3d keypoint, why use 
```
pred_keypoints_3d =pred_keypoints_3d - pred_pelvis
```
and 
```
gt_keypoints_3d = gt_keypoints_3d - gt_pelvis 
```
my question is why minus a broadcast pelvis coordinate?

**Comment by nkolot** [comment]
The evaluation protocols require the pelvis keypoint to be located at [0,0,0], so we subtract the pelvis location, that is essentially translating the keypoints in 3D.

**Comment by liwenssss** [comment]
Thanks for your reply! Another question, I find that Table 4 in the paper use PCK and AUC, but I dont know what are they mean and I don't find code about them.

**Comment by liwenssss** [comment]
SORRY to bother, I just read HMR and get the answer.

**Comment by geopavlakos** [comment]
Regarding the definition of these metrics, we provide more details in the [Supplementary Material](https://www.seas.upenn.edu/~nkolot/projects/spin/files/spin-supp.pdf).
For the computation of the PCK and AUC metrics on the MPI-INF-3DHP dataset, we suggest using the official MATLAB test code provided with the dataset.
