### ISSUE TITLE
how to choose SMPL model

### ISSUE THREAD

**Issue by liwenssss** [nkolot/SPIN#30]
hi , its me again. I still study the evaluation. I fill confused in when evaluate, which model I need choose to get predict smpl vertices and ground truth smpl vertices from man, women or neutral ? I noticed that when generate predict value you choose neutral and when get gt vertices you don't use  neural if we have the gender value. So does it mean we can choose gender if we can predice it, or we just use neutral?
Sorry for my too many question.

**Comment by geopavlakos** [comment]
Our deep network has been trained using the neutral SMPL model, so for prediction you should always use the neutral model. For the ground truth though, some datasets (3DPW), provide gender-specific values, so we do use the gender-specific mesh to generate the ground truth we compare against.

**Comment by liwenssss** [comment]
another question,  in base_dataset I find you get keypoint_gt like this:
```
        # Get 2D keypoints
        try:
            keypoints_gt = self.data['part']
        except KeyError:
            keypoints_gt = np.zeros((len(self.imgname), 24, 3))
        try:
            keypoints_openpose = self.data['openpose']
        except KeyError:
            keypoints_openpose = np.zeros((len(self.imgname), 25, 3))
        self.keypoints = np.concatenate([keypoints_openpose, keypoints_gt], axis=1)
```
I dont know why you add keypoint_openpose. And I find in your another project GraphCMR(I dont read the paper, just find the code is similar), I find that you get keypoint_gt like this:
```
        # Get 2D keypoints
        try:
            self.keypoints = self.data['part']
        except KeyError:
            self.keypoints = np.zeros((len(self.imgname), 24, 3))
```
so why use openpose keypoint or why not?

**Comment by geopavlakos** [comment]
In this project, we use OpenPose keypoints only for the fitting stage (SMPLify in the loop). This is not necessary, but we observed that they improve the fitting procedure, compared to the vanilla annotated keypoints.

**Comment by iammarvelous** [comment]
> In this project, we use OpenPose keypoints only for the fitting stage (SMPLify in the loop). This is not necessary, but we observed that they improve the fitting procedure, compared to the vanilla annotated keypoints.

Does this indicate that the SMPLify would perform better when using openpose than provided ground truth? If so, why is it? Is it due to unreliable ground truth or the different annotated keypoints (eg, nose v.s. top of head)? Since openpose is trained on COCO, I guess at least for COCO, openpose won't be better than ground truth in the fitting procedure?

**Comment by geopavlakos** [comment]
The difference is subtle here. Annotated landmarks are treated by SMPLify as having confidence one. However, 2D annotations are not always perfect. For example, for some datasets, even non-visible keypoints are annotated, with "reasonable" locations, but not always accurate. Similarly, for some keypoints, there is always labeling noise (i.e., the shoulder location varies depending on the annotator). The annotations are not plain wrong, they are just noisy (please also see the [Unite the People paper](https://arxiv.org/pdf/1701.02468.pdf), which gives a nice visualization of this issue in Figure 3a). In most of these cases, OpenPose is also predicting a confidence value, which effectively incorporates this uncertainty about the exact location of a joint, so we can handle the keypoint accordingly, i.e., decrease their weight in the fitting process. So, although OpenPose keypoint detections are not always perfect, they can often improve the fitted result, by providing this confidence value.

**Comment by GloryyrolG** [comment]
> Our deep network has been trained using the neutral SMPL model, so for prediction you should always use the neutral model. For the ground truth though, some datasets (3DPW), provide gender-specific values, so we do use the gender-specific mesh to generate the ground truth we compare against.

Hi @geopavlakos , but it seems the `gender` in the `3dpw_test.npz` are all `m`? See also [the issue](https://github.com/nkolot/ProHMR/issues/25). Thanks.
