### ISSUE TITLE
Training without human3.6

### ISSUE THREAD

**Issue by ikvision** [nkolot/SPIN#32]
When running training:
train.py --name train_example --pretrained_checkpoint=data/model_checkpoint.pt --run_smplify --ignore_3d
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset_extras/h36m_single_train_openpose.npz'

It is not clear which train option to chose to avoid the need of h3.6m data
[https://github.com/nkolot/SPIN/blob/master/utils/train_options.py
](url)

Do you have an estimate of the decrease performance in eval if I train without h3.6m?

**Comment by nkolot** [comment]
Currently there is not a training option without h3.6m. You can generate it using the scripts we provide [here](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/h36m_train.py). However keep in mind that the generated .npz file will **not** include SMPL pose and shape parameters.

**Comment by arturbecker** [comment]
I have tried to get access to the h3.6m dataset for about a year now and no luck. I wonder it the website is still maintained?
Seeing that I can't get the original data, would it be feasible to port the code to use a subset of the dataset, and/or potentially add a newer one like Total Capture? Or at that point would it be easier to start from scratch?

**Comment by ikvision** [comment]
Updating the dataset list without human3.6
Original code  
[https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/datasets/mixed_dataset.py#L12](url)
It would be nice to compare how results should decrease using this version

should be converted to
`
    def __init__(self, options, **kwargs):
        self.dataset_list = ['lsp-orig', 'mpii', 'lspet', 'coco', 'mpi-inf-3dhp']
        self.dataset_dict = {'lsp-orig': 0, 'mpii': 1, 'lspet': 2, 'coco': 3, 'mpi-inf-3dhp': 4}
        self.datasets = [BaseDataset(options, ds, **kwargs) for ds in self.dataset_list]
        total_length = sum([len(ds) for ds in self.datasets])
        length_itw = sum([len(ds) for ds in self.datasets[0:-1]])
        self.length = max([len(ds) for ds in self.datasets])
        """
        Data distribution inside each batch:
        90% ITW - 10% MPI-INF
        """
        self.partition = [.9*len(self.datasets[0])/length_itw,
                          .9*len(self.datasets[1])/length_itw,
                          .9*len(self.datasets[2])/length_itw, 
                          .9*len(self.datasets[3])/length_itw,
                          0.1]
        self.partition = np.array(self.partition).cumsum()

    def __getitem__(self, index):
        p = np.random.rand()
        for i in range(len( self.dataset_list)):
            if p <= self.partition[i]:
                return self.datasets[i][index % len(self.datasets[i])]

    def __len__(self):
        return self.length
`

**Comment by arturbecker** [comment]
Thanks @ikvision. I tried your code but still get the same error as I did with my previous edits:

`(base) root@1cb80e2ec7ea:/home/SPIN# python3 train.py --name train_example --pretrained_checkpoint=data/model_checkpoint.pt --run_smplify
Checkpoint loaded
  0%|                                                                 | 0/50 [00:00<?, ?it/s/home/Datasets/hr_lspet/im09449.png                                  | 0/1507 [00:00<?, ?it/s]
/home/Datasets/hr_lspet/im08113.png

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    trainer.train()
  File "/home/SPIN/utils/base_trainer.py", line 62, in train
    train_data_loader.checkpoint_batch_idx):
  File "/opt/conda/lib/python3.6/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UnboundLocalError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/SPIN/datasets/mixed_dataset.py", line 33, in __getitem__
    return self.datasets[i][index % len(self.datasets[i])]
  File "/home/SPIN/datasets/base_dataset.py", line 189, in __getitem__
    orig_shape = np.array(img.shape)[:2]
UnboundLocalError: local variable 'img' referenced before assignment
`
Does your modifications work for you to train without h3.6m?

**Comment by ikvision** [comment]
Just for Sanity check, is the imgname variable points to an exiting file?
OpenCV when the file is not found returns a None, not an exception:
[https://github.com/nkolot/SPIN/blob/3c5d02bd4549d4d108e0e13bbc5f62e41ae67295/datasets/base_dataset.py#L186](url)
Are you able to read the file with image reader as skimage?

**Comment by arturbecker** [comment]
Hey, I think my config.py is not pointing to the right dataset paths. I'll test it tomorrow!

**Comment by arturbecker** [comment]
@ikvision I am having a hard time getting the 3dhp dataset to work. I tried subsampling the video files into the imageFrames folders, but the training code still looks for the original frame indexes apparently:
`root@10b44e877333:/home/SPIN# python3 train.py --name train_example --pretrained_checkpoint=data/model_checkpoint.pt --run_smplify
Checkpoint loaded
  0%|                                                    | 0/50 [00:00<?, ?it/s3dhp/S8/Seq2/imageFrames/video_4/frame_003597.jpg       | 0/1507 [00:00<?, ?it/s]
3dhp/S6/Seq1/imageFrames/video_6/frame_005028.jpg
3dhp/S3/Seq2/imageFrames/video_6/frame_005379.jpg
3dhp/S5/Seq2/imageFrames/video_7/frame_002426.jpg

Traceback (most recent call last):
  File "train.py", line 7, in <module>
    trainer.train()
  File "/home/SPIN/utils/base_trainer.py", line 62, in train
    train_data_loader.checkpoint_batch_idx):
  File "/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
UnboundLocalError: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/SPIN/datasets/mixed_dataset.py", line 33, in __getitem__
    return self.datasets[i][index % len(self.datasets[i])]
  File "/home/SPIN/datasets/base_dataset.py", line 189, in __getitem__
    orig_shape = np.array(img.shape)[:2]
UnboundLocalError: local variable 'img' referenced before assignment
`
What I make of this is that I would need to find a way to preserve the original frame indexes the code is looking for or I would indeed need to extract all frames, but that would take too much storage space...

**Comment by ikvision** [comment]
Indeed by default opencv extracts frames sequentially, but it can also extract into specific frames:
[https://stackoverflow.com/questions/33650974/opencv-python-read-specific-frame-using-videocapture](url)

**Comment by arturbecker** [comment]
Hey @ikvision you were right!
Using opencv I managed to extract only the necessary frames, but the method is very inefficient (it took me about 10 hours to run). If anyone wants the script, it's on my fork on github: [3dhp_converter.py](https://github.com/arturbecker/SPIN/blob/master/3dhp_converter.py)

**Comment by VVingerfly** [comment]
> self.length = max([len(ds) for ds in self.datasets])

Hi, @ikvision Why use `max` instead of `sum` here? Shouldn't it be `sum` ？

Looking forward to your reply. Thanks.

B.R.

**Comment by andgitchang** [comment]
@arturbecker I'd like to know how results should be looked like without Human3.6M dataset? I also faced the limitations of MoShed Human3.6M. Thank you.
