### ISSUE TITLE
Trouble with reimplementation with GPU support (RTX 2070 Super)

### ISSUE THREAD

**Issue by arturbecker** [nkolot/SPIN#33]
Hello,
thanks for your work and for providing the docker image!
I am unable to run your demo and evaluation codes with the container as is - in order to get GPU support, I am using the option "--gpus all" when running the container. nvidia-smi recognizes it alright, with CUDA 10.1 (same as the host). I think this is why the code doesn't work, since torch 1.1.0 is compiled with CUDA 9. I am having some serious trouble changing the container's version to 9, and would appreciate any insight on the problem.

My outputs:
`root@f17e6a9cbeee:/home/SPIN# python3 demo.py --checkpoint=data/model_checkpoint.pt --img=examples/im1010.jpg
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument
`

`root@f17e6a9cbeee:/home/SPIN# python3 eval.py --checkpoint=data/model_checkpoint.pt --dataset=3dpw --log_freq=20
Traceback (most recent call last):
  File "eval.py", line 32, in <module>
    from utils.part_utils import PartRenderer
  File "/home/SPIN/utils/part_utils.py", line 3, in <module>
    import neural_renderer as nr
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/__init__.py", line 3, in <module>
    from .load_obj import load_obj
  File "/usr/local/lib/python3.6/dist-packages/neural_renderer/load_obj.py", line 8, in <module>
    import neural_renderer.cuda.load_textures as load_textures_cuda
ImportError: /usr/local/lib/python3.6/dist-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`

- Do you think it would be easier to run a torch=1.1.0 container with the correct cuda and cudnn versions, and go from there?
- As far as I understand, neural-renderer is GPU only, right? That would explain why I actually can run the demo code with CPU-only, but not the evaluation code.

**Comment by nkolot** [comment]
1. PyTorch 1.1.0 was compiled from source with CUDA 10.0 and CUDNN 7.0. So if you want to use CUDA 9.0 you should make a new docker image.
2. Yes, neural-renderer is GPU only currently. You could still run the 3D pose evaluation code though if you comment out the renderer-related lines and imports.
