### ISSUE TITLE
24 joint gt superset 

### ISSUE THREAD

**Issue by ikvision** [nkolot/SPIN#39]
I would like to pre-process my dataset into the a preprocessed format as in 
[https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md](url)

As mentioned in the constant file the ground truth annotation needs to be converted to 24 joints:
[https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/constants.py#L10](url)

But it is not clear to me what is the order and the joints name of those 24 joint, I tried to reverse engineer without too much success the coco convertor: 
[https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/coco.py#L11](url)

Can you point me to the superset 24 joint ordered list names

Thank you

**Comment by geopavlakos** [comment]
The order can be inferred from the file constants.py (starting with 'Right Ankle' and ending with 'Right Ear'), but it is probably more clear as it is presented [here](https://github.com/nkolot/GraphCMR/blob/4e57dca4e9da305df99383ea6312e2b3de78c321/config.py#L52).

**Comment by ikvision** [comment]
Thank you for the link, it is super useful
