### ISSUE TITLE
Installing on windows

### ISSUE THREAD

**Issue by EnricoBeltramo** [nkolot/SPIN#4]
I tried to run the demo on Windows.
I found that to work I have to change the demo.py in follow way:

import torch
torch.cuda.current_device() # new line added
from torchvision.transforms import Normalize

otherwise I have a error in CUDA initialitazion. Anyway, I have follow error:
ModuleNotFoundError: No module named 'pyrender.platforms.osmesa'; 'pyrender.platforms' is not a package
I tried to install following the https://pyrender.readthedocs.io/en/latest/install/index.html without success. Any suggestion? 
Thanks

**Comment by EnricoBeltramo** [comment]
> Hi, I had the same problem with osmesa. For me it worked to just comment out #os.environ['PYOPENGL_PLATFORM'] = 'osmesa' in utils.renderer.
> 
> Does not seem to have any consequences so far...

Thanks! I did, but now I have error:
ModuleNotFoundError: No module named 'pyrender.platforms.pyglet'; 'pyrender.platforms' is not a package

I already installed pyglet, but still issue..

**Comment by EnricoBeltramo** [comment]
Ok,
I resolved cloning a local version of pyrender and using it in the SPIN project. I don't know if the problem was some wrong installation of pc (or may be need to install directly from git master).
Just another note:
in imgutils.py line 80
scipy.misc.imresize(new_img, res) was deprecated and so removed from latest version of scipy.
I replaced importing skimage and using:
skimage.transform.resize(new_img, res)

**Comment by ikvision** [comment]
Due to scipy 1.3.1 version, imrotate and imresize should be upgrade:

https://github.com/nkolot/SPIN/blob/277892a91e74af004c74457cd294bd102972f9b0/utils/imutils.py#L76
new_img = scipy.ndimage.rotate(new_img, rot, reshape=False)
#scipy.misc.imresize(new_img, res)
new_img = scipy.resize(new_img, res)

**Comment by willfu** [comment]
it should be import skimage.transform
                   skimage.transform.resize(new_img, res)
The one ikvision mentioned could not work.
