### ISSUE TITLE
Axial limb orientation

### ISSUE THREAD

**Issue by arturbecker** [nkolot/SPIN#40]
Hello,
I would like to use SPIN for my research both because of the high accuracy, and because it implicitly predicts axial limb orientation (e.g. if an arm is pronated or supinated)
![image](https://user-images.githubusercontent.com/42967248/71923089-01391000-316b-11ea-87dc-77746cdc93bc.png)
since this can be retrieved from the SMPL model. That's an advantage over skeleton-based prediction for my research, and I wonder it you ever thought about measuring the orientation accuracy of the model predictions?

**Comment by geopavlakos** [comment]
Unfortunately, most of the available datasets include only ground truth 3D joints, so this is what we typically use for evaluation. The 3DPW dataset is an exception, however we haven't presented any results on limb orientation there. Our code supports inference on 3DPW, so it should be straightforward to evaluate on another metric if you want.
