### ISSUE TITLE
Multi-person key points correspondence 

### ISSUE THREAD

**Issue by ikvision** [nkolot/SPIN#43]
It seems to me that in the coco pre_processed data there are some mismatch between ground_truth_keypoints and open_pose_keypoint.

I would love to know if it is a known issue (that is difficult to eliminate without manual review) or a bug on my side.

gt_coco_img_keypoints -right person is annotated
![image](https://user-images.githubusercontent.com/11877852/72314601-72356780-3644-11ea-8dfc-d54090e498f6.png)
gt_img_keypoints_open_pose - left person is targeted by the prediction
![image](https://user-images.githubusercontent.com/11877852/72314626-82e5dd80-3644-11ea-93a6-063eae481d1f.png)

This mis-match is not very frequent, as most coco image have a single person, but it might affect the 2d re-projection loss and therefore might me the reason for
> --openpose_train_weight', default=0

**Comment by geopavlakos** [comment]
This is a known issue with the current way we assign correspondences. Most of these should be eliminated with a more careful matching, but this is the original data we used. I don't think there is a bug on your side.
