### ISSUE TITLE
dim size mismatch error running demo.py

### ISSUE THREAD

**Issue by threedlife** [nkolot/SPIN#44]
I came across similar issue as #36 

I downloaded "Version 1.0" of SMPL-X a few days ago, and tried with both Python3.6 and 3.7 in virtualenv as indicated in issue #36 . However, it still reports dimension mismatch errors. 
```
 Traceback (most recent call last):
  File "demo.py", line 129, in <module>
    pred_output = smpl(betas=pred_betas, body_pose=pred_rotmat[:,1:], global_orient=pred_rotmat[:,0].unsqueeze(1), pose2rot=False)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/co/work/SPIN/models/smpl.py", line 23, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/lbs.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/smplx/lbs.py", line 265, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/home/co/work/SPIN/spin-venvpy36/lib/python3.6/site-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2
```
Versions of dependencies are:
```
Package                 Version    
----------------------- -----------
absl-py                 0.9.0      
cachetools              4.0.0      
certifi                 2019.11.28 
chardet                 3.0.4      
chumpy                  0.69       
cycler                  0.10.0     
decorator               4.4.1      
ffnet                   0.8.4      
freetype-py             2.1.0.post1
future                  0.18.2     
google-auth             1.10.0     
google-auth-oauthlib    0.4.1      
grpcio                  1.26.0     
h5py                    2.10.0     
idna                    2.8        
imageio                 2.6.1      
kiwisolver              1.1.0      
Markdown                3.1.1      
matplotlib              3.1.2      
networkx                2.2        
neural-renderer-pytorch 1.1.3      
numpy                   1.18.1     
oauthlib                3.1.0      
opencv-python           4.1.2.30   
Pillow                  6.1.0      
pip                     19.3.1     
protobuf                3.11.2     
pyasn1                  0.4.8      
pyasn1-modules          0.2.8      
pyglet                  1.4.0b1    
PyOpenGL                3.1.0      
pyparsing               2.4.6      
pyrender                0.1.33     
python-dateutil         2.8.1      
PyWavelets              1.1.1      
requests                2.22.0     
requests-oauthlib       1.3.0      
rsa                     4.0        
scikit-image            0.16.2     
scipy                   1.0.0      
setuptools              44.0.0     
six                     1.13.0     
smplx                   0.1.13     
spacepy                 0.2.1      
tensorboard             2.0.2      
torch                   1.1.0      
torchgeometry           0.1.2      
torchvision             0.3.0      
tqdm                    4.41.1     
trimesh                 3.5.14     
urllib3                 1.25.7     
Werkzeug                0.16.0     
wheel                   0.33.6 
```

Any idea what is wrong here?

_Originally posted by @threedlife in https://github.com/nkolot/SPIN/issues/36#issuecomment-573270965_

**Comment by threedlife** [comment]
After further look into the code, it seems the error occurred because the pretrained model returns pred_rotmat in 3x3 rotation matrix form, however full_pose of body_models.py accepts angle axis values as input (jaw/hand/eye values are in angle axis form)
```
full_pose = torch.cat([global_orient, body_pose,
                               jaw_pose, leye_pose, reye_pose,
                               left_hand_pose,
                               right_hand_pose], dim=1)
```

I used kornia.rotation_matrix_to_angle_axis to convert the rotation matrix into angle axis. Then it reported another dim mismatch error. After digging into it, I found that the pretrained model returns 23 body poses (I suppose it's same as SMPL kinematic tree), but SMPL-X accepts 21 poses. 

I passed the first 21 body poses (with left-, right- hand poses) into full_pose and finally it worked. But the result pose was totally messed up. 
![im1010_shape](https://user-images.githubusercontent.com/43429119/72418091-2229e280-37b5-11ea-8b01-7f0a625fd1f3.png)
![im1010_shape_side](https://user-images.githubusercontent.com/43429119/72418092-2229e280-37b5-11ea-865b-1be684b2b375.png)


I guess it has something to do with the selection and order of the 21 body poses? Any help is appreciated!

**Comment by nkolot** [comment]
There is a bug in the kornia.rotation_matrix_to_angle_axis function.
Please look at the relevant issue [here](https://github.com/kornia/kornia/issues/317).

**Comment by pangyyyyy96** [comment]
@threedlife I'm facing the same issue, have you found the fix for it yet?

**Comment by vigneshrk29** [comment]
@threedlife I too am facing the same issue. Have you found a fix yet?

**Comment by colincqian** [comment]
@threedlife @pangyyyyy96 @vigneshrk29 @nkolot  I am facing the same issue. Any fix around that? I have spent a long time trying to fix this

**Comment by yqq-jj** [comment]
@threedlife I  am facing the same issue. Could you tell me how to solve it?

Traceback (most recent call last):
  File "demo.py", line 120, in <module>
    pred_output = smpl(betas=pred_betas, body_pose=pred_rotmat[:,1:], global_orient=pred_rotmat[:,0].unsqueeze(1), pose2rot=False)
  File "/root/anaconda3/envs/spin/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/yuanQi/spin/models/smpl.py", line 23, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/root/anaconda3/envs/spin/lib/python3.6/site-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/root/anaconda3/envs/spin/lib/python3.6/site-packages/smplx/lbs.py", line 179, in lbs
    v_shaped = v_template + blend_shapes(betas, shapedirs)
  File "/root/anaconda3/envs/spin/lib/python3.6/site-packages/smplx/lbs.py", line 265, in blend_shapes
    blend_shape = torch.einsum('bl,mkl->bmk', [betas, shape_disps])
  File "/root/anaconda3/envs/spin/lib/python3.6/site-packages/torch/functional.py", line 211, in einsum
    return torch._C._VariableFunctions.einsum(equation, operands)
RuntimeError: size of dimension does not match previous size, operand 1, dim 2

**Comment by ken012git** [comment]
Hi folks,

I think the problem was in the old version of smplx implementation. Just add one line `shapedirs = shapedirs[:, :, :self.NUM_BETAS]` in `shapedirs = shapedirs[:, :, :self.NUM_BETAS]` to make the code work. 

`$ vim /usr/local/lib/python3.6/dist-packages/smplx/body_models.py`

```
272         # The shape components
273         shapedirs = data_struct.shapedirs
274         shapedirs = shapedirs[:, :, :self.NUM_BETAS]   # add this line. check the latest implementation from smplx https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py#L167
275         # The shape components
276         self.register_buffer(
277             'shapedirs',
278             to_tensor(to_np(shapedirs), dtype=dtype))
```

![im1010_shape_side](https://user-images.githubusercontent.com/9960543/199616784-15179a42-aafa-4be9-8380-6f50beb6ca96.png)
![im1010_shape](https://user-images.githubusercontent.com/9960543/199616786-977f53f6-a445-4e04-8b3a-e7aa5162a49b.png)
![im1010](https://user-images.githubusercontent.com/9960543/199616788-76893d56-b255-4368-95bb-64c3ddfec80e.jpg)

**Comment by wmj142326** [comment]
> Hi folks,
> 
> If you are using the docker provided from this github, I think the problem was in the old version of smplx implementation. Just add one line in to make the code work.`shapedirs = shapedirs[:, :, :self.NUM_BETAS]``smplx/body_models.py`
> 
> `$ vim /usr/local/lib/python3.6/dist-packages/smplx/body_models.py`
> 
> ```
> 272         # The shape components
> 273         shapedirs = data_struct.shapedirs
> 274         shapedirs = shapedirs[:, :, :self.NUM_BETAS]   # add this line. check the latest implementation from smplx https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py#L167
> 275         # The shape components
> 276         self.register_buffer(
> 277             'shapedirs',
> 278             to_tensor(to_np(shapedirs), dtype=dtype))
> ```
> 
> ![im1010_shape_side](https://user-images.githubusercontent.com/9960543/199616784-15179a42-aafa-4be9-8380-6f50beb6ca96.png) ![im1010_shape](https://user-images.githubusercontent.com/9960543/199616786-977f53f6-a445-4e04-8b3a-e7aa5162a49b.png) ![im1010](https://user-images.githubusercontent.com/9960543/199616788-76893d56-b255-4368-95bb-64c3ddfec80e.jpg)

Surprise! I used your method and it worked!！！！
