### ISSUE TITLE
Warnning issues with pytorch1.3

### ISSUE THREAD

**Issue by cenalzw** [nkolot/SPIN#47]
Hello, thanks a lot for your contribution. 
When I run the train.py code, I see a lot of warning message like:

/pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.

However, I have no idea where the warnings could be from, I will really appreciate that if you can give me any advice about that, thank you!

**Comment by ikvision** [comment]
The solution for this warning is in https://github.com/nkolot/SPIN/commit/21a148d29ea99627bd24cd51997d1484986c196e

**Comment by QuteSaltyFish** [comment]
> Hello, thanks a lot for your contribution.
> When I run the train.py code, I see a lot of warning message like:
> 
> /pytorch/aten/src/ATen/native/IndexingUtils.h:20: UserWarning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead.
> 
> However, I have no idea where the warnings could be from, I will really appreciate that if you can give me any advice about that, thank you!

hello，could you run the eval.py with torch1.3? I've built the env my self bu always get import error
"ImportError: /root/miniconda3/envs/py36/lib/python3.6/site-packages/neural_renderer/cuda/load_textures.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E
"
