### ISSUE TITLE
input to camera_fitting_loss

### ISSUE THREAD

**Issue by maartenjv** [nkolot/SPIN#5]
Hello,

I was going trough the code for camera_fitting_loss.py and was wondering why this was defined as it is:

reprojection_error_op = (joints_2d[:, op_joints_ind, :-1] - projected_joints[:, op_joints_ind, :]) ** 2

specifically, why are only the x-values of joints_2d used here (:-1). I believe joints_2d has shape (batch, #joints, 2) --> (x,y), as in simplify.py the input to the loss is defined as:

#Get joint confidence
        joints_2d = keypoints_2d[:, :, :2]
        joints_conf = keypoints_2d[:, :, -1]

Thx!

**Comment by nkolot** [comment]
Yes, you are correct. I fixed that and pushed the changes.
