### ISSUE TITLE
Render Error during Training

### ISSUE THREAD

**Issue by QuteSaltyFish** [nkolot/SPIN#50]
Traceback (most recent call last):                                                                                                              | 99/4877 [09:26<6:57:33,  5.24s/it]
  File "train.py", line 7, in <module>
    trainer.train()
  File "/home/project/SPIN/utils/base_trainer.py", line 72, in train
    self.train_summaries(batch, *out)
  File "/home/project/SPIN/train/trainer.py", line 305, in train_summaries
    images_pred = self.renderer.visualize_tb(pred_vertices, pred_cam_t, images)
  File "/home/project/SPIN/utils/renderer.py", line 29, in visualize_tb
    rend_img = torch.from_numpy(np.transpose(self.__call__(vertices[i], camera_translation[i], images_np[i]), (2,0,1))).float()
  File "/home/project/SPIN/utils/renderer.py", line 46, in __call__
    mesh.apply_transform(rot)
  File "/usr/local/lib/python3.6/dist-packages/trimesh/base.py", line 2038, in apply_transform
    triangle_pre = self.vertices[self.faces[:5]]
IndexError: index 1 is out of bounds for axis 0 with size 0

**Comment by QuteSaltyFish** [comment]
This may imply that during training, the network may not predict the right amount of vertices?

**Comment by QuteSaltyFish** [comment]
I implement the training process using sgd and momentum, is this problem generated from this?

**Comment by ikvision** [comment]
I seems that a some stage of the training self.vertices is empty
Does it happen on the first batch of epoch 0?
I don't think it is related to the sgd or momentum, the regression should generated pose and shape that should generate skin vertices even for random weights

**Comment by nkolot** [comment]
This appears to be an issue with trimesh. If it's very early in training you can potentially get large values for the vertices that could introduce numerical instabilities. I've never seen this issue in my setup. I would suggest adding a try-except block and manually debug what's the issue.

**Comment by wolterlw** [comment]
In my experience this error happens when all the predictions in the batch are invalid and cannot be rendered (possibly because of invalid values). This usually happens when the network is initialized badly or the learning rate is too large, because if regressor weights are initialized as close to 0 your prediction should be close to `(init_pose, init_shape, init_cam)`, which are valid.
