### ISSUE TITLE
Real time Demo

### ISSUE THREAD

**Issue by Hwang-dae-won** [nkolot/SPIN#51]
Thank you for awesome work.

Is it possible to demo in real time?

**Comment by ikvision** [comment]
Real time is quite ambiguous term. 
The demo runs frame by frame (batch size=1) on my cpu in 0.2 seconds. Does it meet your requirements?

**Comment by Hwang-dae-won** [comment]
I got it.

Thank you for your reply

2020년 1월 29일 (수) 오후 3:09, ik_vision <notifications@github.com>님이 작성:
