### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by lan786** [nkolot/SPIN#54]
@nkolot  Hi, thanks so much for such a nice work. I tried to run using virtual environment but I'm unable to run. I want to run it in Docker but I'm new in Docker. Docker is working and I already fetched your repository. What is next procedure to run the demo? I'm very sorry for this very basic question. 
Thanks for your support.

**Comment by arturbecker** [comment]
Hi, if you already fetched the image, and you are in Linux, try this on the terminal:

docker run -it --shm-size='16gb' --gpus all -p 8888:8888 chaneyk/spin

There's some flare in this command to give access to RAM (replace the '16gb' value with what you'd like), letting docker access the gpus and opening the 8888 port (useful if you plan to run jupyter notebooks from inside the container)

**Comment by lan786** [comment]
@arturbecker  Thanks for your kind response.
