### ISSUE TITLE
Camera Model

### ISSUE THREAD

**Issue by liren2515** [nkolot/SPIN#55]
@nkolot Hi, I have a question about the camera model. I saw that you first estimated the parameters [s, tx, ty] for a weak perspective camera, then you converted it to cam translation by [tx, ty, 2f/(img_res*s)]. Instead of directly regress the translation from the model, why do you first estimate [s, tx, ty] and then do this conversion? And how do you derive the formula for tz as tz=2f/(img_res*s)?

**Comment by nkolot** [comment]
So this conversion is already used in HMR for visualization. It's one way of interpreting the weak perspective parameters [s,tx,ty] as a representation for the actual 3D translation given a fixed focal length.
