### ISSUE TITLE
About the optimization part in the training time of Huamn3.6M

### ISSUE THREAD

**Issue by ll961546784** [nkolot/SPIN#56]
Hi. It's a great job, but I'm a little confused, In your code, the optimized parameters are replaced with the ground truth parameters, if they are available. So, dose that mean, that the optimization part of the code dosen't work during training on the Huamn3.6M?

**Comment by ikvision** [comment]
According to https://github.com/nkolot/SPIN/issues/11
For H36M the SMPLify process has no effect

**Comment by ll961546784** [comment]
If the SMPLify process has no effect, the whole network is same as the HMR. However, in Table 3, SPIN's performance is better.

**Comment by nkolot** [comment]
So just to clarify, if there are "ground truth" parameters available these override any parameters obtained for the optimization. This is the case in H36M. The performance increase for Human3.6M does not come from improved supervision in Human3.6M but rather from improved supervision in the other datasets where the optimization is actually used.

**Comment by ll961546784** [comment]
I got it, thanks!
