### ISSUE TITLE
loss for camera parameters

### ISSUE THREAD

**Issue by xuxy09** [nkolot/SPIN#6]
Hi,

I have a question regarding the loss function.

In trainer.py, there is no explicit loss function for the predicted camera parameters. Since you are maintaining the "opt_camera_t" in the dictionary, it looks more reasonable and straightforward to add a loss to explicitly restrict the camera parameters (similar to "End-to-end recovery of human shape and pose", CVPR18). 

Have you tried this in your experiments? Will it improve performance or not?

Thanks!

**Comment by nkolot** [comment]
We did not choose to apply a loss on the camera parameters directly, but it is definitely a thing you could try. By the way the paper you are referencing did not had explicit loss on the camera parameters. We followed what they did, i.e. learn the camera through the joints reprojection.

**Comment by xuxy09** [comment]
Thanks for your reply.

Indeed, this CVPR18 paper did not use any explicit loss for camera parameters. Maybe they use the camera parameters in the discriminator, which is not relevant here since you did not include GAN in your work. 

Still, I am not absolutely sure why you maintain the "opt_cam_t" in the dictionary, which seems somehow useless in the project. Could you please elaborate more on this? Thanks!

**Comment by nkolot** [comment]
Actually we do not save it in the dictionary. The reason we compute it is to do the visualization later on Tensorboard.
