### ISSUE TITLE
Order of predicted joint output, and reasoning behind the use of a joint regressor

### ISSUE THREAD

**Issue by arturbecker** [nkolot/SPIN#61]
I have a question about the evaluation of MPJPE on 3dpw.

My understanding from **eval.py** is that instead of using the SMPL ground truth joints provided in **gt_pose**, instead, a mesh is generated (**gt_vertices**), and fed into the **J_regressor_h36m**, the output of which is reordered using **constants.H36M_TO_J14**.

My first question is: what is the order of such 14 joints? I couldn't make it out from the constants.py file.

and secondly, why is the MPJPE evaluated like so in 3dpw if a full 24 joint comparison from the "native" SMPL joints on the ground-truth and on the prediction is possible?

**Comment by nkolot** [comment]
We evaluated on the 14 common joints instead of the 24 because this is what most prior work did and we wanted to be directly comparable with them.
The joints are 'Right Ankle' to 'Left Elbow' + 'Head (H36m)'.
