### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset_extras/h36m_train.npz'

### ISSUE THREAD

**Issue by GuiZhaoyang** [nkolot/SPIN#63]
When I run training code has this error,
FileNotFoundError: [Errno 2] No such file or directory: 'data/dataset_extras/h36m_train.npz'
Does someone know where can i get this file?

**Comment by nkolot** [comment]
We do not provide any Human3.6M data due to licensing issues. You have to register in their website and then run our preprocessing scripts to generate them.

**Comment by yqq-jj** [comment]
Could you tell me how you solve it?@GuiZhaoyang

**Comment by yqq-jj** [comment]
Could you tell me how you solve it?@GuiZhaoyang
