### ISSUE TITLE
Issue in running demo.py

### ISSUE THREAD

**Issue by giuli13** [nkolot/SPIN#64]
Hi! I tried to run the file demo.py but I got this error:

> ValueError: Failed to initialize Pyglet window with an OpenGL >= 3+ context. If you're logged in via SSH, ensure that you're running your script with vglrun (i.e. VirtualGL). The internal error message was ""
How can I solve it? Thanks a lot!

**Comment by nkolot** [comment]
Did you try to run it on your local machine or on a remote server / cluster?
What is your OS? Are you using a virtual environment or maybe docker?

**Comment by giuli13** [comment]
I run it in a remote server with a virtual machine. The OS is Ubuntu and I am using a python virtual environment.

**Comment by nkolot** [comment]
In this case you need to install either OSmesa or EGL and use this as the backend for pyrender. This code uses OSMesa by default. For more info please take a look [here](https://pyrender.readthedocs.io/en/latest/).

**Comment by ankitsharma07** [comment]
I am on macOS and I am not able to find OSmesa for it. What would be recommended solution to this?
Also, I was trying to run demo.py using docker image. How can I move the SMPLify model to it? I have downloaded it to my local environment
