### ISSUE TITLE
cannot reproduce the results with from-scratch training

### ISSUE THREAD

**Issue by xuxy09** [nkolot/SPIN#66]
Hi,

I have prepared all the datasets needed including H36M, and trained the models with the code in this repo. However, I cannot reproduce the results in the paper. The recons error on 3DPW is about 70 while the one reported in the paper is lower than 60. 
Can anybody give more details about this issue?

**Comment by nkolot** [comment]
Can you elaborate more?
How did you train your model exactly? For example number of training iterations etc.

**Comment by xuxy09** [comment]
I simply use the code provided by the repo without any modification. I run the training from scratch by:
"python train.py --name train_example --run_smplify"

I train the model for 10^6 iterations with the default batch size 64. However, I find the training almost saturates at 2*10^5 iterations, and further training only very marginally improves the performance.

**Comment by xuxy09** [comment]
In addition, according to the supplement, training with "final_dict" should produce similar results to training with "run_smplify". However, I find this strategy does not give as good results as reported in the paper either. The best recons. error I can get for 3DPW is 67 while the number is less than 60 in the paper.

**Comment by Ironbrotherstyle** [comment]
> 

Same question. Maybe the released model was trained on 3dpw so that it performances well on the test split.

**Comment by ltphuongunited** [comment]
Hi @xuxy09, can you help me for using H36M during training? Please give me your email.

**Comment by 124518** [comment]
@xuxy09 Hellow, Did you use Openpose to process the data during the reproduction process?Or just use data to train? Looking forward to your reply
