### ISSUE TITLE
loss regression pose

### ISSUE THREAD

**Issue by ikvision** [nkolot/SPIN#68]
I think pose_loss_weight is not missing the aggregation of the loss during training

https://github.com/nkolot/SPIN/blob/b4c70d526585e8d7d1f9910064d5e73ffa71b63a/train/trainer.py#L258

It should be fix easily
```python
self.options.pose_loss_weight * loss_regr_pose + self.options.beta_loss_weight * loss_regr_betas
```

It would not change the default run as :
https://github.com/nkolot/SPIN/blob/64e4c08682f9cb78103de8d31718dd30f542eccf/utils/train_options.py#L44

**Comment by nkolot** [comment]
You can open a PR for this and I will merge it.
