### ISSUE TITLE
failed to install neural-renderer-pytorch

### ISSUE THREAD

**Issue by LH-Abner** [nkolot/SPIN#7]
I try to install the neural-renderer-pytorch in win10 ,python3.6 with torch==1.1.0 , but failed.
This is the part of error .  And I can not find the solution,.
`ERROR: Command errored out with exit status 1:
   command: 'C:\Users\LH\AppData\Local\Programs\Python\Python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LH\\AppData\\Local\\Temp\\pip-install-ccvzskvd\\neural-renderer-pytorch\\setup.py'"'"'; __file__='"'"'C:\\Users\\LH\\AppData\\Local\\Temp\\pip-install-ccvzskvd\\neural-renderer-pytorch\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LH\AppData\Local\Temp\pip-wheel-cyg0cn7b' --python-tag cp36
       cwd: C:\Users\LH\AppData\Local\Temp\pip-install-ccvzskvd\neural-renderer-pytorch\
  Complete output (1140 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\get_points_from_angles.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\lighting.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\load_obj.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\look.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\look_at.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\mesh.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\perspective.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\projection.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\rasterize.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\renderer.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\save_obj.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\vertices_to_faces.py -> build\lib.win-amd64-3.6\neural_renderer
  copying neural_renderer\__init__.py -> build\lib.win-amd64-3.6\neural_renderer
  creating build\lib.win-amd64-3.6\neural_renderer\cuda
  copying neural_renderer\cuda\__init__.py -> build\lib.win-amd64-3.6\neural_renderer\cuda
  running build_ext
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\cpp_extension.py:184: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的文件。
    warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
  building 'neural_renderer.cuda.load_textures' extension
  creating build\temp.win-amd64-3.6
  creating build\temp.win-amd64-3.6\Release
  creating build\temp.win-amd64-3.6\Release\neural_renderer
  creating build\temp.win-amd64-3.6\Release\neural_renderer\cuda
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -IC:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include -IC:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\TH -IC:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -IC:\Users\LH\AppData\Local\Programs\Python\Python36\include -IC:\Users\LH\AppData\Local\Programs\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\Include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" /EHsc /Tpneural_renderer/cuda/load_textures_cuda.cpp /Fobuild\temp.win-amd64-3.6\Release\neural_renderer/cuda/load_textures_cuda.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=load_textures -D_GLIBCXX_USE_CXX11_ABI=0 /MD
  cl: 命令行 warning D9025 :正在重写“/MT”(用“/MD”)
  load_textures_cuda.cpp
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(27): warning C4275: 非 dll 接口 class“std::exception”用作 dll 接口 class“c10::Error”的基
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\vcruntime_exception.h(44): note: 参见“std::exception”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(27): note: 参见“c10::Error”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(28): warning C4251: “c10::Error::msg_stack_”: class“std::vector<std::string,std::allocator<_Ty>>”需要有 dll 接口由 class“c10::Error”的客户端使用
          with
          [
              _Ty=std::string
          ]
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(28): note: 参见“std::vector<std::string,std::allocator<_Ty>>”的声明
          with
          [
              _Ty=std::string
          ]
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(29): warning C4251: “c10::Error::backtrace_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“c10::Error”的客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(34): warning C4251: “c10::Error::msg_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“c10::Error”的客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Exception.h(35): warning C4251: “c10::Error::msg_without_backtrace_”: class“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”需要有 dll 接口由 class“c10::Error”的客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xstring(4373): note: 参见“std::basic_string<char,std::char_traits<char>,std::allocator<char>>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/Allocator.h(21): warning C4251: “c10::DataPtr::ptr_”: class“c10::detail::UniqueVoidPtr”需要有 dll 接口由 class“c10::DataPtr”的客户端使用
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/UniqueVoidPtr.h(38): note: 参见“c10::detail::UniqueVoidPtr”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/Allocator.h(183): warning C4251: “c10::InefficientStdFunctionContext::ptr_”: class“std::unique_ptr<void,std::function<void (void *)>>”需要有 dll 接口由 struct“c10::InefficientStdFunctionContext”的客户端使用
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/Allocator.h(183): note: 参见“std::unique_ptr<void,std::function<void (void *)>>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/TensorTypeIdRegistration.h(32): warning C4251: “c10::TensorTypeIdCreator::last_id_”: struct“std::atomic<unsigned char>”需要有 dll 接口由 class“c10::TensorTypeIdCreator”的 客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xxatomic(162): note: 参见“std::atomic<unsigned char>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/TensorTypeIdRegistration.h(45): warning C4251: “c10::TensorTypeIdRegistry::registeredTypeIds_”: class“std::unordered_set<c10::TensorTypeId,std::hash<c10::TensorTypeId>,std::equal_to<_Kty>,std::allocator<_Kty>>”需要有 dll 接口由 class“c10::TensorTypeIdRegistry”的客户端使用
          with
          [
              _Kty=c10::TensorTypeId
          ]
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/TensorTypeIdRegistration.h(45): note: 参见“std::unordered_set<c10::TensorTypeId,std::hash<c10::TensorTypeId>,std::equal_to<_Kty>,std::allocator<_Kty>>”的声明
          with
          [
              _Kty=c10::TensorTypeId
          ]
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/TensorTypeIdRegistration.h(46): warning C4251: “c10::TensorTypeIdRegistry::mutex_”: class“std::mutex”需要有 dll 接口由 class“c10::TensorTypeIdRegistry”的客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\mutex(82): note: 参见“std::mutex”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(168): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(171): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(174): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(177): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(181): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(184): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(187): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(190): warning C4244: “参数”: 从“int”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(196): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(199): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(202): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(205): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(209): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(212): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(215): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/Half-inl.h(218): warning C4244: “参数”: 从“int64_t”转换到“float”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/intrusive_ptr.h(58): warning C4251: “c10::intrusive_ptr_target::refcount_”: struct“std::atomic<unsigned __int64>”需要有 dll 接口由 class“c10::intrusive_ptr_target”的客户端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xxatomic(162): note: 参见“std::atomic<unsigned __int64>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/intrusive_ptr.h(59): warning C4251: “c10::intrusive_ptr_target::weakcount_”: struct“std::atomic<unsigned __int64>”需要有 dll 接口由 class“c10::intrusive_ptr_target”的客户 端使用
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\Include\xxatomic(162): note: 参见“std::atomic<unsigned __int64>”的声明
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/intrusive_ptr.h(723): warning C4267: “return”: 从“size_t”转换到“uint32_t”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/util/intrusive_ptr.h(757): warning C4267: “return”: 从“size_t”转换到“uint32_t”，可能丢失数据
  C:\Users\LH\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\include\c10/core/Storage.h(181): warning C4251: “c10::Storage::storage_impl_”: class“c10::intrusive_ptr<c10::StorageImpl,c10::detail::intrusive_target_default_null_type<TTarget>>”需要有 dll 接口由 struct“c10::Storage”的客户端使用`

**Comment by EnricoBeltramo** [comment]
I had a error installing on win10 me too.
I successfully installed taking original source code and doing changes proposed in:
https://github.com/daniilidis-group/neural_renderer/issues/47
