### ISSUE TITLE
Pre-trained model checkpoint for unpaired setting.

### ISSUE THREAD

**Issue by akashsengupta1997** [nkolot/SPIN#70]
Hi,

Would it be possible to get access to a pre-trained model checkpoint trained using the "unpaired" setting (i.e. without training data of images paired with 3D GT), without having to re-train the model myself? This would be greatly appreciated!

**Comment by nkolot** [comment]
Hi Akash,
Unfortunately we do not have such a checkpoint available for releasing :(

**Comment by akashsengupta1997** [comment]
No worries :)
