### ISSUE TITLE
3D mesh size increase

### ISSUE THREAD

**Issue by durgesh17media** [nkolot/SPIN#82]
How do we increase the resolution of generated 3D mesh? It's always 224*224 which is really tiny to perform any calculation on it.

**Comment by ikvision** [comment]
Can you elaborate which calculation your try to perform on the mesh?
I am asking as the generated mesh in not in the 2d image space (cropped and resized to 224x224), but in normalized 3d coordinate system.

**Comment by durgesh17media** [comment]
@ikvision I am trying to calculate body measurement from 3D meshlike waist size bust size etc

**Comment by nkolot** [comment]
These calculations should be done on the mesh and not in the projected image.
