### ISSUE TITLE
Mesh generated for thin and fat person is same only

### ISSUE THREAD

**Issue by durgesh17media** [nkolot/SPIN#85]
how can we generate a 3D mesh which has evident difference for a thin and fat person?

**Comment by ikvision** [comment]
One intuition of betas is that the first component mainly influences the height and the second one more body volume.
As the PCA process to generate the decomposition is unsupervised, this is an intuition that may not hold in many cases.
But playing with the beta's first two components should have the majority of the effect on 3d mesh body shape.
