### ISSUE TITLE
Mapping SPIN joints to SMPL

### ISSUE THREAD

**Issue by feemthan** [nkolot/SPIN#86]
Hello,

Thanks for the amazing work on this repo.

Wanted to know how to map the joints given in the smplx layer in this repo to the base smpl model. I have seen the constants.py file but still is unclear as some of the joints in SMPLx are not present in SMPL. SMPLx gives 48 poses(some are openpose as shown in constants.py), while SMPL needs 24.
Regards.

**Comment by nkolot** [comment]
Our output consists of some of the joints of the SMPL kinematic tree plus some additional points (e.g. eyes, ears, nose) that are not part of the SMPL kinematic tree but can be regressed from the vertices. This is why you see a different number of output joints.
