### ISSUE TITLE
h36m SMPL parameters

### ISSUE THREAD

**Issue by GuiZhaoyang** [nkolot/SPIN#87]
I have had the Mosh data for h36m dataset. Then how can I get the SMPL parameters for h36m dataset

**Comment by Z-Z-J** [comment]
@GuiZhaoyang  Do you know how to get the SMPL parameters for h36m dataset now ???  Thanks!!

**Comment by cenalzw** [comment]
@GuiZhaoyang Could you please tell me the way to get Mosh data of hm3.6? Do I need to write a code to generate it or download it directly? I have no idea. Looking forward to your help!
