### ISSUE TITLE
cannot import name 'ModelOutput' from 'smplx.body_models'

### ISSUE THREAD

**Issue by mirakim227** [nkolot/SPIN#89]
Hi ! thanks for the great work.
I encountered this error while trying your demo code. 

Traceback (most recent call last):
  File "demo.py", line 34, in <module>
    from models import hmr, SMPL
  File "/home/ubuntu/anaconda3/envs/test/SPIN/models/__init__.py", line 2, in <module>
    from .smpl import SMPL
  File "/home/ubuntu/anaconda3/envs/test/SPIN/models/smpl.py", line 5, in <module>
    from smplx.body_models import ModelOutput
ImportError: cannot import name 'ModelOutput' from 'smplx.body_models' (/home/ubuntu/anaconda3/lib/python3.8/site-packages/smplx/body_models.py)

I noticed that there is no class named 'ModelOutput' in smplx.body_models. 
Since I'm new to pytorch, I think that maybe I missed something. 
I'd really appreciate your help, or even some hints 

Thanks in advance!

**Comment by RaraKim** [comment]
I changed 'ModelOutput' to 'SMPLX' and still wonder that it's okay!

**Comment by uyoung-jeong** [comment]
It seems that smplx repository has updated its code to use distinct model output for each SMPL type(SMPL, SMPLH, SMPLX). 

https://github.com/vchoutas/smplx/blob/master/smplx/utils.py

I think that replacing `ModelOutput` with `SMPLOutput` will work.

**Comment by shyanguan** [comment]
pip install smpl=0.1.13
