### ISSUE TITLE
/Project/Internal_Overlay/SPIN/spin/lib/python3.6/site-packages/pyrender/platforms/osmesa.py", line 19, in init_context     from OpenGL.osmesa import ( ImportError: cannot import name 'OSMesaCreateContextAttribs'

### ISSUE THREAD

**Issue by g-gaurav** [nkolot/SPIN#9]
osmesa is installed but not able to use this. pleas help

**Comment by LH-Abner** [comment]
I had the same problem.

**Comment by nkolot** [comment]
What OS are you using?

**Comment by LH-Abner** [comment]
@nkolot  I run the demo.py in ubuntu 16.0.4 with python3.x.

**Comment by anuragranj** [comment]
```sh
sudo apt-get install libosmesa6-dev
```

**Comment by anuragranj** [comment]
A way around is to comment this line:
https://github.com/nkolot/SPIN/blob/master/utils/renderer.py#L2

**Comment by huybery** [comment]
This problem still exists after installing libosmesa6-dev, 
```
  File "/home/mesh/voca/utils/voca_model.py", line 274, in _render_helper
    self._render_sequences_helper(video_fname, raw_audio[i_seq], processed_audio[i_seq], templates[i_seq], vertices[i_seq], condition_idx)
  File "/home/mesh/voca/utils/voca_model.py", line 306, in _render_sequences_helper
    gt_img = render_mesh_helper(Mesh(seq_verts[i_frame], self.template_mesh.f), center)
  File "/home/mesh/voca/utils/rendering.py", line 108, in render_mesh_helper
    r = pyrender.OffscreenRenderer(viewport_width=frustum['width'], viewport_height=frustum['height'])
  File "/home/mesh/.virtualenvs/voca/lib/python3.6/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/mesh/.virtualenvs/voca/lib/python3.6/site-packages/pyrender/offscreen.py", line 134, in _create
    self._platform.init_context()
  File "/home/mesh/.virtualenvs/voca/lib/python3.6/site-packages/pyrender/platforms/osmesa.py", line 19, in init_context
    from OpenGL.osmesa import (
ImportError: cannot import name 'OSMesaCreateContextAttribs'

```


```
> glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on llvmpipe (LLVM 3.8, 256 bits)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 11.2.0
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 11.2.0
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

How can i fixed it ?

**Comment by shangliy** [comment]
@huybery 
You may need to install the compatible version of Opengl;

> git clone git@github.com:mmatl/pyopengl.git
> pip install ./pyopengl

Refer: [install](https://pyrender.readthedocs.io/en/latest/install/index.html#installing-osmesa)

**Comment by JackSyu** [comment]
@huybery 
I had the same problem. Did you solve it?

**Comment by Shannon33** [comment]
I had the same problem.  I already install:
git clone git@github.com:mmatl/pyopengl.git
pip install ./pyopengl
and I try : Sudo apt-get install libosmesa6-dev
still doesn't work

**Comment by DYF-AI** [comment]
I have the same problem. I solved the problem,
You should uninstall pyopengl and restart to install the new one,
For example, before my pyopengl version is 3.1.0, (ImportError: Cannot import the name'OSMesaCreateContextAttribs')
After I reinstalled version 3.1.5 of pyopengl, the problem was solved

**Comment by krips89** [comment]
> @huybery
> You may need to install the compatible version of Opengl;
> 
> > git clone [git@github.com](mailto:git@github.com):mmatl/pyopengl.git
> > pip install ./pyopengl
> 
> Refer: [install](https://pyrender.readthedocs.io/en/latest/install/index.html#installing-osmesa)

Installing this pyopengl gives  me the following error:

`File "demo.py", line 115, in <module>
    renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl.faces)
  File "/HPS/impl_deep_volume/static00/SPIN/utils/renderer.py", line 17, in __init__
    point_size=1.0)
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/offscreen.py", line 150, in _create
    self._platform.make_current()
  File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/platforms/osmesa.py", line 44, in make_current
    self.viewport_width, self.viewport_height
AssertionError
`

**Comment by jacquelinelala** [comment]
> > @huybery
> > You may need to install the compatible version of Opengl;
> > > git clone [git@github.com](mailto:git@github.com):mmatl/pyopengl.git
> > > pip install ./pyopengl
> > 
> > 
> > Refer: [install](https://pyrender.readthedocs.io/en/latest/install/index.html#installing-osmesa)
> 
> Installing this pyopengl gives me the following error:
> 
> `File "demo.py", line 115, in <module> renderer = Renderer(focal_length=constants.FOCAL_LENGTH, img_res=constants.IMG_RES, faces=smpl.faces) File "/HPS/impl_deep_volume/static00/SPIN/utils/renderer.py", line 17, in __init__ point_size=1.0) File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__ self._create() File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/offscreen.py", line 150, in _create self._platform.make_current() File "/HPS/impl_deep_volume/static00/home/anaconda2/envs/p37n/lib/python3.7/site-packages/pyrender/platforms/osmesa.py", line 44, in make_current self.viewport_width, self.viewport_height AssertionError`

Same Assertion error. Have you Fixed it? @krips89

**Comment by Wyz2927** [comment]
> I have the same problem. I solved the problem, You should uninstall pyopengl and restart to install the new one, For example, before my pyopengl version is 3.1.0, (ImportError: Cannot import the name'OSMesaCreateContextAttribs') After I reinstalled version 3.1.5 of pyopengl, the problem was solved

How can I get the 3.1.5 version of pyopengl? the link given is for 3.1.0. looking forward for your reply

**Comment by ywx-stack** [comment]
I solved the same questions by
`pip uninstall pyopengl`
`pip install pyopengl==3.1.5`
there are still some other erros ,but this question maybe have been sovled.

**Comment by Bodhi007** [comment]
(spin) 20lzw@compute:~/SPIN$ pip install --upgrade pyopengl
Requirement already satisfied: pyopengl in /home/20lzw/.conda/envs/spin/lib/python3.6/site-packages (3.1.0)
Collecting pyopengl
  Downloading PyOpenGL-3.1.6-py3-none-any.whl (2.4 MB)
     |████████████████████████████████| 2.4 MB 28 kB/s             
Installing collected packages: pyopengl
  Attempting uninstall: pyopengl
    Found existing installation: PyOpenGL 3.1.0
    Uninstalling PyOpenGL-3.1.0:
      Successfully uninstalled PyOpenGL-3.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyrender 0.1.45 requires PyOpenGL==3.1.0, but you have pyopengl 3.1.6 which is incompatible.
Successfully installed pyopengl-3.1.6

**Comment by ai1urus** [comment]
https://github.com/nkolot/SPIN/issues/9#issuecomment-611327421
https://github.com/nkolot/SPIN/issues/9#issuecomment-810878169
kami sama

**Comment by lllllialois** [comment]
> I solved the same questions by `pip uninstall pyopengl` `pip install pyopengl==3.1.5` there are still some other erros ,but this question maybe have been sovled.

after I install pyopengl==3.1.5
I meet new question
ing = cv2.imread(img_file)[:, : , : :-l] .copy () # PyTorch does not support negative stride at the moment
TypeError: 'NoneType ' object is not subscriptable
have u met this question？

**Comment by lllllialois** [comment]
> > I solved the same questions by `pip uninstall pyopengl` `pip install pyopengl==3.1.5` there are still some other erros ,but this question maybe has been solved.
> 
> after I install pyopengl==3.1.5 I meet new question ing = cv2.imread(img_file)[:, : , : :-l] .copy () # PyTorch does not support negative stride at the moment TypeError: 'NoneType ' object is not subscriptable have u met this question？

ok I have .jpg but I cv.imread .png. so it read nothing.
By the way, install pyopengl==3.1.5 instead of 3.1.0, it works well!

**Comment by wangxihao** [comment]
> I solved the same questions by `pip uninstall pyopengl` `pip install pyopengl==3.1.5` there are still some other erros ,but this question maybe have been sovled.

I also solved it!

**Comment by wangxihao** [comment]
> 

absl-py                 0.13.0
astroid                 2.9.0
cachetools              4.2.2
certifi                 2021.5.30
charset-normalizer      2.0.4
chumpy                  0.70
cycler                  0.10.0
freetype-py             2.2.0
google-auth             1.34.0
google-auth-oauthlib    0.4.5
grpcio                  1.39.0
idna                    3.2
imageio                 2.9.0
importlib-metadata      4.6.3
isort                   5.9.3
kiwisolver              1.3.1
lazy-object-proxy       1.6.0
Markdown                3.3.4
matplotlib              3.4.2
mccabe                  0.6.1
networkx                2.6.2
neural-renderer         1.1.3
neural-renderer-pytorch 1.1.3
numpy                   1.21.1
oauthlib                3.1.1
opencv-python           4.5.3.56
pandas                  1.3.5
Pillow                  9.1.0
pip                     21.2.3
platformdirs            2.4.0
protobuf                3.17.3
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyglet                  1.5.18
pylint                  2.12.1
PyOpenGL                3.1.5
pyparsing               2.4.7
pyrender                0.1.45
python-dateutil         2.8.2
pytz                    2022.1
PyWavelets              1.1.1
PyYAML                  6.0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-image            0.18.2
scipy                   1.2.1
seaborn                 0.11.2
setuptools              57.4.0
six                     1.16.0
smplx                   0.1.13
tensorboard             2.6.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tifffile                2021.8.8
toml                    0.10.2
torch                   1.11.0
torchgeometry           0.1.2
torchvision             0.12.0
tqdm                    4.62.0
trimesh                 3.9.27
typed-ast               1.4.3
typing-extensions       3.10.0.0
urllib3                 1.26.6
Werkzeug                2.0.1
wheel                   0.37.0
wrapt                   1.12.1
zipp                    3.5.0
