### ISSUE TITLE
Render the output on the original image 

### ISSUE THREAD

**Issue by ku294714** [nkolot/SPIN#90]
Hello Dear @nkolot ,

How do i render the results on the original image and not just on image with resolution of 224.

Regards,
Ankit

**Comment by ikvision** [comment]
VIBE is rendering on the original image resolution https://github.com/mkocabas/VIBE/blob/master/demo.py#L256-L314

**Comment by ku294714** [comment]
@ikvision Thank you, I have got it work. I have one more question, for the static fits, you trained another offline model.

To regress pose and beta, which datasets did you use for training?

Regards,
Ankit

**Comment by nkolot** [comment]
As we mention in Section 1. of the [Supplementary material](https://www.seas.upenn.edu/~nkolot/projects/spin/files/spin-supp.pdf), we trained it on the CMU Mocap dataset.

**Comment by qizhuli** [comment]
@ku294714 Hi Ankit, would you be able to share how you managed to render on the original resolution image? Many thanks!
