### ISSUE TITLE
Duplicate images in pre-processed training datasets

### ISSUE THREAD

**Issue by hakanyi** [nkolot/SPIN#92]
After downloading the `data/dataset_extras` and inspecting the dataset, I noticed that there are duplicate image names (at least for MPII). For example, 'images/088121273.jpg' is contained three times:
```python
data = np.load("data/dataset_extras/mpii_train.npz")['imgname']
np.where(test == 'images/088121273.jpg')
>>> (array([11137, 11138, 11139]),)
```
Consequently, the corresponding data are duplicated in the final fits in `spin_fits.tar.gz` where duplicate data have dissimilar pose and shape vectors.
It seems that this bug (?) is introduced in the preprocessing stage, I haven't found it though.

**Comment by geopavlakos** [comment]
MPII images contain more than one humans per image, so if an image name is repeated, it probably means that this dataset entry corresponds to a different person instance. You could also check the 'center' and 'scale' values (for this particular example, they refer to different bounding boxes).

**Comment by hakanyi** [comment]
Ah, that makes sense. Thanks so much @geopavlakos!
