### ISSUE TITLE
Why use 49 key points, these 49 key points have many repetitive points

### ISSUE THREAD

**Issue by ysp568** [nkolot/SPIN#94]

**Comment by nkolot** [comment]
Yes, there are some duplicate keypoints. The reason we did this is that we wanted to have the OpenPose keypoints and the ground truth annotations separately in the keypoint list.

**Comment by ysp568** [comment]
> Yes, there are some duplicate keypoints. The reason we did this is that we wanted to have the OpenPose keypoints and the ground truth annotations separately in the keypoint list.
Thank you
